name: Deploy DAG and JAR to GCP

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK for SBT
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set Up SBT
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Build JAR with SBT
        run: sbt clean assembly

      - name: Print Current Active Account
        run: |
          gcloud auth login gzymeri55@gmail.com
          echo "Current active account before authentication:"
          gcloud config get-value account || echo "No active account set"

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Check GCS Access
        run: |
          echo "Checking GCS access:"
          gsutil ls gs://github-act

      - name: List files in DAGs directory
        run: |
          echo "Listing files in DAGs directory:"
          ls -alh $GITHUB_WORKSPACE/dags/

      - name: Upload DAG to GCP Bucket
        run: |
          echo "Attempting to upload DAG:"
          gsutil cp $GITHUB_WORKSPACE/dags/hello_world_dag.py gs://github-act/dags/

      - name: Check if JAR file exists
        run: |
          echo "Checking if JAR file exists:"
          ls -alh $GITHUB_WORKSPACE/target/scala-2.13/ || echo "JAR directory not found"

      - name: Upload JAR to GCP Bucket
        run: |
          echo "Attempting to upload JAR file:"
          gsutil cp $GITHUB_WORKSPACE/target/scala-2.13/*.jar gs://github-act/jars/
        if: success()

      - name: Trigger Airflow DAG Run (Optional)
        env:
          AIRFLOW_URL: ${{ secrets.AIRFLOW_URL }}
          AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
          AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
        run: |
          echo "Triggering Airflow DAG Run:"
          curl -X POST "$AIRFLOW_URL/api/v1/dags/hello_world_dag/dagRuns" \
          -H "Content-Type: application/json" \
          --user "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
          -d '{"conf": {}}'
